//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.BLL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarRental.BLL.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Car.
        /// </summary>
        public static string AddCar {
            get {
                return ResourceManager.GetString("AddCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have added new reservation!.
        /// </summary>
        public static string AddedReservation {
            get {
                return ResourceManager.GetString("AddedReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        public static string AdminDashboard {
            get {
                return ResourceManager.GetString("AdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Contidion.
        /// </summary>
        public static string AirCondition {
            get {
                return ResourceManager.GetString("AirCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set air condition.
        /// </summary>
        public static string AirConditionRequired {
            get {
                return ResourceManager.GetString("AirConditionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ascending.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentification page.
        /// </summary>
        public static string AuthPage {
            get {
                return ResourceManager.GetString("AuthPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Transmission.
        /// </summary>
        public static string AutomaticTransmission {
            get {
                return ResourceManager.GetString("AutomaticTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have canceled  reservation!.
        /// </summary>
        public static string CanseledReservation {
            get {
                return ResourceManager.GetString("CanseledReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be in range from 1 to 5.
        /// </summary>
        public static string CapacityRange {
            get {
                return ResourceManager.GetString("CapacityRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input capacity.
        /// </summary>
        public static string CapacityRequired {
            get {
                return ResourceManager.GetString("CapacityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Info.
        /// </summary>
        public static string CarInfo {
            get {
                return ResourceManager.GetString("CarInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car issuance.
        /// </summary>
        public static string CarIssuance {
            get {
                return ResourceManager.GetString("CarIssuance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car park management(Admin).
        /// </summary>
        public static string CarManagment {
            get {
                return ResourceManager.GetString("CarManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Name.
        /// </summary>
        public static string CarName {
            get {
                return ResourceManager.GetString("CarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Return.
        /// </summary>
        public static string CarReturn {
            get {
                return ResourceManager.GetString("CarReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        public static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class of the car.
        /// </summary>
        public static string CarType {
            get {
                return ResourceManager.GetString("CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input class of the car.
        /// </summary>
        public static string CarTypeRequired {
            get {
                return ResourceManager.GetString("CarTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Manager.
        /// </summary>
        public static string CreateManager {
            get {
                return ResourceManager.GetString("CreateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string DeleteWarning {
            get {
                return ResourceManager.GetString("DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descending.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door.
        /// </summary>
        public static string Door {
            get {
                return ResourceManager.GetString("Door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value between 1 and 10.
        /// </summary>
        public static string DoorRange {
            get {
                return ResourceManager.GetString("DoorRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Licence.
        /// </summary>
        public static string DriverLicence {
            get {
                return ResourceManager.GetString("DriverLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string DriverNecessity {
            get {
                return ResourceManager.GetString("DriverNecessity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Unit.
        /// </summary>
        public static string DriveUnit {
            get {
                return ResourceManager.GetString("DriveUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Drive Unit type.
        /// </summary>
        public static string DriveUnitRequired {
            get {
                return ResourceManager.GetString("DriveUnitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dysel.
        /// </summary>
        public static string Dysel {
            get {
                return ResourceManager.GetString("Dysel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Econom.
        /// </summary>
        public static string Econom {
            get {
                return ResourceManager.GetString("Econom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Car.
        /// </summary>
        public static string EditCar {
            get {
                return ResourceManager.GetString("EditCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero cars have been found mathing your request..
        /// </summary>
        public static string EmptyCarSear {
            get {
                return ResourceManager.GetString("EmptyCarSear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order list is empty.
        /// </summary>
        public static string EmptyOrders {
            get {
                return ResourceManager.GetString("EmptyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero users have been found mathing your request..
        /// </summary>
        public static string EmptyUserSear {
            get {
                return ResourceManager.GetString("EmptyUserSear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return car.
        /// </summary>
        public static string EndPlace {
            get {
                return ResourceManager.GetString("EndPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Rent.
        /// </summary>
        public static string EndRent {
            get {
                return ResourceManager.GetString("EndRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Capacity.
        /// </summary>
        public static string EngineCapacity {
            get {
                return ResourceManager.GetString("EngineCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input engine capacity.
        /// </summary>
        public static string EngineCapacityRequired {
            get {
                return ResourceManager.GetString("EngineCapacityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Details.
        /// </summary>
        public static string ExceptionDetails {
            get {
                return ResourceManager.GetString("ExceptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exeption management (Admin).
        /// </summary>
        public static string ExceptionManagment {
            get {
                return ResourceManager.GetString("ExceptionManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine.
        /// </summary>
        public static string Fine {
            get {
                return ResourceManager.GetString("Fine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fines.
        /// </summary>
        public static string Fines {
            get {
                return ResourceManager.GetString("Fines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of your fines.
        /// </summary>
        public static string FinesPage {
            get {
                return ResourceManager.GetString("FinesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four-Wheel.
        /// </summary>
        public static string FourWheelDrive {
            get {
                return ResourceManager.GetString("FourWheelDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front-Wheel.
        /// </summary>
        public static string FrontWheel {
            get {
                return ResourceManager.GetString("FrontWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel consump..
        /// </summary>
        public static string FuelConsumption {
            get {
                return ResourceManager.GetString("FuelConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Input fuel consumption.
        /// </summary>
        public static string FuelConsumptionRequired {
            get {
                return ResourceManager.GetString("FuelConsumptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Type.
        /// </summary>
        public static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Input Fuel Type.
        /// </summary>
        public static string FuelTypeRequired {
            get {
                return ResourceManager.GetString("FuelTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Licence.
        /// </summary>
        public static string Licence {
            get {
                return ResourceManager.GetString("Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Comment.
        /// </summary>
        public static string ManagerComment {
            get {
                return ResourceManager.GetString("ManagerComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Dashboard.
        /// </summary>
        public static string ManagerDashboard {
            get {
                return ResourceManager.GetString("ManagerDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input manufactorer.
        /// </summary>
        public static string ManufacturerRequired {
            get {
                return ResourceManager.GetString("ManufacturerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model name.
        /// </summary>
        public static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Orders.
        /// </summary>
        public static string MyOrders {
            get {
                return ResourceManager.GetString("MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input name.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any fines. Thanks for careful driving..
        /// </summary>
        public static string NoFinesMessage {
            get {
                return ResourceManager.GetString("NoFinesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any orders.
        /// </summary>
        public static string NoOrdersMessage {
            get {
                return ResourceManager.GetString("NoOrdersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order management (Manager).
        /// </summary>
        public static string OrderManagment {
            get {
                return ResourceManager.GetString("OrderManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order sum.
        /// </summary>
        public static string OrdSum {
            get {
                return ResourceManager.GetString("OrdSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payed.
        /// </summary>
        public static string Payed {
            get {
                return ResourceManager.GetString("Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment page.
        /// </summary>
        public static string PaymentPage {
            get {
                return ResourceManager.GetString("PaymentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol.
        /// </summary>
        public static string Petrol {
            get {
                return ResourceManager.GetString("Petrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleage.
        /// </summary>
        public static string Pleage {
            get {
                return ResourceManager.GetString("Pleage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string Popular {
            get {
                return ResourceManager.GetString("Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        public static string Premium {
            get {
                return ResourceManager.GetString("Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per day.
        /// </summary>
        public static string PricePerDay {
            get {
                return ResourceManager.GetString("PricePerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be more than 0.
        /// </summary>
        public static string PriceRange {
            get {
                return ResourceManager.GetString("PriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Details.
        /// </summary>
        public static string ProfileDetails {
            get {
                return ResourceManager.GetString("ProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rear-Wheel.
        /// </summary>
        public static string RearWheel {
            get {
                return ResourceManager.GetString("RearWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Time.
        /// </summary>
        public static string RentTime {
            get {
                return ResourceManager.GetString("RentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent with pleage.
        /// </summary>
        public static string RentWithPleage {
            get {
                return ResourceManager.GetString("RentWithPleage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select .
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select manufactorer.
        /// </summary>
        public static string SelectCarManuf {
            get {
                return ResourceManager.GetString("SelectCarManuf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take car.
        /// </summary>
        public static string StartPlace {
            get {
                return ResourceManager.GetString("StartPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartRent.
        /// </summary>
        public static string StartRent {
            get {
                return ResourceManager.GetString("StartRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out information about recent orders(Admin/Manager).
        /// </summary>
        public static string StatisticManagment {
            get {
                return ResourceManager.GetString("StatisticManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been successfully registrated..
        /// </summary>
        public static string SuccessfullyRegistered {
            get {
                return ResourceManager.GetString("SuccessfullyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car List .
        /// </summary>
        public static string TotalCars {
            get {
                return ResourceManager.GetString("TotalCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exeption occured .
        /// </summary>
        public static string TotalException {
            get {
                return ResourceManager.GetString("TotalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total orders .
        /// </summary>
        public static string TotalOrders {
            get {
                return ResourceManager.GetString("TotalOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list .
        /// </summary>
        public static string TotalUsers {
            get {
                return ResourceManager.GetString("TotalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string TransAuto {
            get {
                return ResourceManager.GetString("TransAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string TransManual {
            get {
                return ResourceManager.GetString("TransManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission.
        /// </summary>
        public static string Transmission {
            get {
                return ResourceManager.GetString("Transmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select transmission type.
        /// </summary>
        public static string TransmissionRequired {
            get {
                return ResourceManager.GetString("TransmissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your login and password to log in our website.
        /// </summary>
        public static string UseLoginPassword {
            get {
                return ResourceManager.GetString("UseLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User management(Admin).
        /// </summary>
        public static string UserManagment {
            get {
                return ResourceManager.GetString("UserManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without pleage.
        /// </summary>
        public static string WithoutPleage {
            get {
                return ResourceManager.GetString("WithoutPleage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Driver Licence.
        /// </summary>
        public static string YourDriverLicence {
            get {
                return ResourceManager.GetString("YourDriverLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your orders.
        /// </summary>
        public static string YourOrders {
            get {
                return ResourceManager.GetString("YourOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Phone.
        /// </summary>
        public static string YourPhone {
            get {
                return ResourceManager.GetString("YourPhone", resourceCulture);
            }
        }
    }
}
